[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }
indicatif = "0.18.0"
rand = "0.9.2"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "renderer_benchmark"
harness = false

